### ISSUE TITLE
Exception in CLion 2017.3

### ISSUE THREAD

**Issue by chrkv** [Darkyenus/glsl4idea#134]
CLion 173.4674, GLSL Support 1.16
```
<< java.lang.StackOverflowError
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getFirstChild(ASTDelegatePsiElement.java:101)
	at com.intellij.psi.impl.PsiElementBase.findChildrenByClass(PsiElementBase.java:293)
	at glslplugin.lang.elements.expressions.GLSLOperatorExpression.getOperands(GLSLOperatorExpression.java:47)
	at glslplugin.lang.elements.expressions.GLSLSubscriptExpression.getArrayExpression(GLSLSubscriptExpression.java:48)
	at glslplugin.lang.elements.expressions.GLSLSubscriptExpression.getType(GLSLSubscriptExpression.java:86)
	at glslplugin.lang.elements.declarations.GLSLDeclarator.clarifyArrayType(GLSLDeclarator.java:139)
	at glslplugin.lang.elements.declarations.GLSLDeclarator.getType(GLSLDeclarator.java:189)
... 
	at glslplugin.lang.elements.expressions.GLSLIdentifierExpression.getType(GLSLIdentifierExpression.java:94)
	at glslplugin.lang.elements.expressions.GLSLSubscriptExpression.getType(GLSLSubscriptExpression.java:88)
	at glslplugin.lang.elements.declarations.GLSLDeclarator.clarifyArrayType(GLSLDeclarator.java:139)
	at glslplugin.lang.elements.declarations.GLSLDeclarator.getType(GLSLDeclarator.java:189)
...
  3000 times
...  
	at glslplugin.annotation.impl.VariableTypeHighlightAnnotation.annotate(VariableTypeHighlightAnnotation.java:24)
	at glslplugin.annotation.impl.VariableTypeHighlightAnnotation.annotate(VariableTypeHighlightAnnotation.java:18)
	at glslplugin.annotation.Annotator.annotateGeneric(Annotator.java:46)
	at glslplugin.annotation.GLSLAnnotator.annotate(GLSLAnnotator.java:80)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:371)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:303)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:333)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:333)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:239)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by Darkyenus** [comment]
Thanks for the report! Could you please supply a file which caused this and steps to reproduce? (Feel free to simplify the file or send it via email, if you don't want it publicly visible.)

**Comment by Darkyenus** [comment]
Please reopen with a GLSL code that reproduces the issue.
