### ISSUE TITLE
Convert Vector Components does not work

### ISSUE THREAD

**Issue by Darkyenus** [Darkyenus/glsl4idea#34]
**Example:**
```
    vec2 a = vec2(1.0).xy;
```
* Cursor on `xy`
* Alt-Enter - Convert Vector Components

**Result:**

```
java.lang.ClassCastException: com.intellij.psi.impl.source.tree.LeafPsiElement cannot be cast to glslplugin.lang.elements.GLSLIdentifier
	at glslplugin.intentions.vectorcomponents.VectorComponentsIntention$1$1.run(VectorComponentsIntention.java:84)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:38)
	at com.intellij.openapi.command.WriteCommandAction$2$1.run(WriteCommandAction.java:114)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:937)
	at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:111)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:108)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:80)
	at glslplugin.intentions.vectorcomponents.VectorComponentsIntention$1.run(VectorComponentsIntention.java:87)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
```

**Comment by AbigailBuccaneer** [comment]
The PSI tree presumably just used to end in a `GLSLIdentifier`, but now it consists of a `GLSLIdentifier` which contains a `LeafPsiElement` with `elementType = IDENTIFIER`.

**Comment by AbigailBuccaneer** [comment]
It should be possible to duct-tape this by just calling `PsiTreeUtil#getChildOfType` in `VectorComponentsIntention`, but I don't see any reason for the tree to look like that in the first place.
